export const IMAGES = {
  logo: require("../assets/images/logo.png"),
  logoText: require("../assets/images/logoText.png"),
  headerLogo: require("../assets/images/headerLogo.png"),
  onBoardingImg: require("../assets/images/onBoardingImg.png"),
  onboardingLogo: require("../assets/images/onboardingLogo.png"),
  eyeOn: require("../assets/images/eyeOn.png"),
  eyeOff: require("../assets/images/eyeOff.png"),
  filterLocation: require("../assets/images/filterLocation.png"),
  backButton: require("../assets/images/backButton.png"),
  arToEng: require("../assets/images/arToEng.png"),
  engToAr: require("../assets/images/engToAr.png"),
  settings: require("../assets/images/account.png"),
  promoIcon: require("../assets/images/promoIcon.png"),
  homeHeaderImg: require("../assets/images/homeHeaderImg.png"),
  pr1: require("../assets/images/pr1.png"),
  pr2: require("../assets/images/pr2.png"),
  pr3: require("../assets/images/pr3.png"),
  pr4: require("../assets/images/pr4.png"),
  pr5: require("../assets/images/pr5.png"),
};
